CREATE TABLE User(
  id_user bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname varchar(20),
  lastname varchar(20),
  email varchar(20),
  active boolean,
  dateOfBirth varchar(20),
  nickname varchar(20),
  login varchar(20),
  password varchar(20),
  avatar blob
);

ALTER TABLE User ADD CONSTRAINT id_role FOREIGN KEY (id_role) REFERENCES Role(id_role) ON DELETE CASCADE
ALTER TABLE User ADD CONSTRAINT id_address FOREIGN KEY (id_address) REFERENCES Address(id_address) ON DELETE CASCADE

CREATE TABLE Terminal(
  id_terminal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(20),
  available boolean
);

CREATE TABLE Role(
  id_role bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role varchar(20)
);

CREATE TABLE News(
  id_news bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body varchar(300),
  uploadDate date
);

ALTER TABLE News ADD CONSTRAINT id_user FOREIGN KEY (id_user) REFERENCES User(id_user) ON DELETE CASCADE

CREATE TABLE Address(
  id_address bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city varchar(20),
  postalCode varchar(6),
  street varchar(30)
);

-- CREATE TABLE Reservation(
-- id_reservation bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  