CREATE TABLE Role(
  idRole bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role varchar(20)
);

CREATE TABLE Address(
  idAddress bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city varchar(20),
  postalCode varchar(6),
  street varchar(30),
  localnumber varchar(5)
);

CREATE TABLE User(
  idUser bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname varchar(20),
  lastname varchar(20),
  email varchar(20),
  active boolean,
  dateOfBirth varchar(20),
  nickname varchar(20),
  login varchar(20),
  password varchar(20),
  avatar blob,
  role_IDROLE bigint, FOREIGN KEY (role_IDROLE) REFERENCES Role(IDROLE),
  address_IDADDRESS bigint, FOREIGN KEY (address_IDADDRESS) REFERENCES Address(IDADDRESS)
);

CREATE TABLE Terminal(
  idTerminal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(20),
  description varchar(100),
  available boolean
);


CREATE TABLE News(
  idNews bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(50),
  body varchar(300),
  uploadDate date,
  user_IDUSER bigint, FOREIGN KEY (user_IDUSER) REFERENCES User(IDUSER)
);

CREATE TABLE Rents(
  idRents bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dateOfRent varchar(20),
  timeOfRent int,
  priceOfRent double,
  user_IDUSER bigint, FOREIGN KEY (user_IDUSER) REFERENCES User(IDUSER),
  terminal_IDTERMINAL bigint, FOREIGN KEY (terminal_IDTERMINAL) REFERENCES Terminal(IDTERMINAL)
);

INSERT INTO ROLE(ROLE) VALUES('ROLE_ADMIN');

INSERT INTO ROLE(ROLE) VALUES('ROLE_USER');

INSERT INTO "PUBLIC"."USER"
( "FIRSTNAME", "LASTNAME", "EMAIL", "ACTIVE", "DATEOFBIRTH", "NICKNAME", "LOGIN", "PASSWORD", "AVATAR", "ROLE_IDROLE" )
VALUES ('Marcin', 'Hallman', 'mhallman94@gmail.com',true, '1994-10-06', 'Strugacki', 'admin', 'admin123',null,0);

INSERT INTO News(title,body,uploadDate,user_IDUSER) VALUES('Turniej League of Legends','W najbliższy weekend w CyberCafe odbędzie się turniej League of Legends dla graczy z całej Polski. Na uczestników czekają upominki a na zwycięzców wspaniałe nagrody ufundowane przez Intela. Zapraszamy!!','2016-02-12',0);

INSERT INTO News(title,body,uploadDate,user_IDUSER) VALUES('Turniej CS:GO','W najbliższy weekend w CyberCafe odbędzie się turniej CS:GO dla graczy z całej Polski. Na uczestników czekają upominki a na zwycięzców wspaniałe nagrody ufundowane przez Intela. Zapraszamy!!','2016-02-12',0);

INSERT INTO News(title,body,uploadDate,user_IDUSER) VALUES('Rozpoczęcie działalności','CyberCafe, miejsce, w którym możesz się zrelaksować grając na konsoli i PC ze znajomymi właśnie rozpoczęło działalność. Zapraszamy!!','2016-02-12',0);

