CREATE TABLE Role(
  idRole bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role varchar(20)
);

CREATE TABLE User(
  idUser bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname varchar(20),
  lastname varchar(20),
  email varchar(20),
  active boolean,
  dateOfBirth varchar(20),
  nickname varchar(20),
  login varchar(20),
  password varchar(20),
  avatar blob,
  role_IDROLE bigint, FOREIGN KEY (role_IDROLE) REFERENCES Role(IDROLE)
);

INSERT INTO ROLE(ROLE) VALUES('ROLE_ADMIN')

INSERT INTO "PUBLIC"."USER"
( "FIRSTNAME", "LASTNAME", "EMAIL", "ACTIVE", "DATEOFBIRTH", "NICKNAME", "LOGIN", "PASSWORD", "AVATAR", "ROLE_IDROLE" )
VALUES ('Marcin', 'Hallman', 'mhallman94@gmail.com',true, '1994-10-06', 'Strugacki', 'admin', 'admin123',null,0)

CREATE TABLE Address(
  idAddress bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city varchar(20),
  postalCode varchar(6),
  street varchar(30)
);

ALTER TABLE User ADD CONSTRAINT idRole FOREIGN KEY (idRole) REFERENCES Role(idRole) ON DELETE CASCADE
ALTER TABLE User ADD CONSTRAINT idAddress FOREIGN KEY (idAddress) REFERENCES Address(idAddress) ON DELETE CASCADE

CREATE TABLE Terminal(
  idTerminal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(20),
  available boolean
);


CREATE TABLE News(
  idNews bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(50),
  body varchar(300),
  uploadDate date
);

ALTER TABLE News ADD CONSTRAINT idUser FOREIGN KEY (idUser) REFERENCES User(idUser) ON DELETE CASCADE


INSERT INTO News(title,body,uploadDate) VALUES('Turniej League of Legends','W najbliższy weekend w CyberCafe odbędzie się turniej League of Legends dla graczy z całej Polski. Na uczestników czekają upominki a na zwycięzców wspaniałe nagrody ufundowane przez Intela. Zapraszamy!!','2016-02-12');

INSERT INTO News(title,body,uploadDate) VALUES('Turniej CS:GO','W najbliższy weekend w CyberCafe odbędzie się turniej CS:GO dla graczy z całej Polski. Na uczestników czekają upominki a na zwycięzców wspaniałe nagrody ufundowane przez Intela. Zapraszamy!!','2016-02-12');

INSERT INTO News(title,body,uploadDate) VALUES('Rozpoczęcie działalności','CyberCafe, miejsce, w którym możesz się zrelaksować grając na konsoli i PC ze znajomymi właśnie rozpoczęło działalność. Zapraszamy!!','2016-02-12');

